### ISSUE TITLE
typing not required in python > 3.5

### ISSUE THREAD

**Issue by clavigne** [rigetti/rpcq#97]
The typing library is not required for python 3.5. Specifically, see https://github.com/python/typing/issues/573 . 

As of right now, this causes psi4 (commonly used with OpenFermion, commonly used with Pyquil, which requires typing) to break immediately when executed.

```
(p4env) $ psi4
Traceback (most recent call last):
  File "/h/182/clavigne/anaconda3/envs/p4env/bin/psi4", line 177, in <module>
    import psi4
  File "/h/182/clavigne/anaconda3/envs/p4env/lib//python3.7/site-packages/psi4/__init__.py", line 82, in <module>
    from .driver import endorsed_plugins
  File "/h/182/clavigne/anaconda3/envs/p4env/lib//python3.7/site-packages/psi4/driver/__init__.py", line 33, in <module>
    from qcelemental import constants
  File "/h/182/clavigne/anaconda3/envs/p4env/lib//python3.7/site-packages/qcelemental/__init__.py", line 6, in <module>
    from . import covalent_radii, models, molparse, molutil, periodic_table, physical_constants, util, vanderwaals_radii
  File "/h/182/clavigne/anaconda3/envs/p4env/lib//python3.7/site-packages/qcelemental/covalent_radii.py", line 7, in <module>
    from typing import Dict, Union
  File "/h/182/clavigne/anaconda3/envs/p4env/lib//python3.7/site-packages/typing.py", line 1357, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/h/182/clavigne/anaconda3/envs/p4env/lib//python3.7/site-packages/typing.py", line 1005, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'
```

The error can be fixed by updating requirements.txt as such,
`typing; python_version < '3.5'`

**Comment by appleby** [comment]
Thanks for reporting this. We actually only support python >= 3.6, so I think it's safe to just remove it. Testing a fix now.
